<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $cats = Category::pluck('id', 'slug');
        $brands = Brand::pluck('id', 'slug');

        $products = [
            // 1
            [
                'name' => 'MSI Titan GT77 Gaming Laptop',
                'slug' => 'msi-titan-gt77-gaming-laptop',
                'sku' => 'MSI-GT77-001',
                'category_id' => $cats['laptops'],
                'brand_id' => $brands['msi'],
                'price' => 85000.00,
                'sale_price' => null,
                'stock' => 10,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => 'The MSI Titan GT77 is the ultimate gaming laptop with desktop-class performance.',
                'specs' => [
                    'Processor' => ['CPU' => 'Intel Core i9-13980HX', 'Cores' => '24'],
                    'Memory' => ['RAM' => '64GB DDR5'],
                    'Storage' => ['SSD' => '2TB NVMe RAID0'],
                    'Display' => ['Size' => '17.3 inch', 'Resolution' => '3840x2160', 'Refresh Rate' => '144Hz'],
                    'Graphics' => ['GPU' => 'NVIDIA RTX 4090 16GB'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 2
            [
                'name' => 'ASUS ROG Zephyrus G15',
                'slug' => 'asus-rog-zephyrus-g15',
                'sku' => 'ASUS-G15-001',
                'category_id' => $cats['laptops'],
                'brand_id' => $brands['asus'],
                'price' => 72000.00,
                'sale_price' => 65000.00,
                'stock' => 8,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => 'Slim, powerful, and stunning – the ROG Zephyrus G15 redefines gaming laptops.',
                'specs' => [
                    'Processor' => ['CPU' => 'AMD Ryzen 9 7945HX', 'Cores' => '16'],
                    'Memory' => ['RAM' => '32GB DDR5'],
                    'Storage' => ['SSD' => '1TB NVMe'],
                    'Display' => ['Size' => '15.6 inch', 'Resolution' => '2560x1440', 'Refresh Rate' => '240Hz'],
                    'Graphics' => ['GPU' => 'NVIDIA RTX 4080 12GB'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 3
            [
                'name' => 'MSI Creator M16',
                'slug' => 'msi-creator-m16',
                'sku' => 'MSI-CM16-001',
                'category_id' => $cats['laptops'],
                'brand_id' => $brands['msi'],
                'price' => 58000.00,
                'sale_price' => null,
                'stock' => 5,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => true,
                'description' => 'A creator-focused laptop with Mini LED display and RTX graphics.',
                'specs' => [
                    'Processor' => ['CPU' => 'Intel Core i7-13700H', 'Cores' => '14'],
                    'Memory' => ['RAM' => '32GB DDR5'],
                    'Storage' => ['SSD' => '1TB NVMe'],
                    'Display' => ['Size' => '16 inch', 'Resolution' => '3840x2400', 'Type' => 'Mini LED'],
                    'Graphics' => ['GPU' => 'NVIDIA RTX 4070 8GB'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 4
            [
                'name' => 'ASUS VivoBook 15',
                'slug' => 'asus-vivobook-15',
                'sku' => 'ASUS-VB15-001',
                'category_id' => $cats['laptops'],
                'brand_id' => $brands['asus'],
                'price' => 28000.00,
                'sale_price' => null,
                'stock' => 15,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Everyday laptop with solid performance for students and professionals.',
                'specs' => [
                    'Processor' => ['CPU' => 'Intel Core i5-1235U', 'Cores' => '10'],
                    'Memory' => ['RAM' => '16GB DDR4'],
                    'Storage' => ['SSD' => '512GB NVMe'],
                    'Display' => ['Size' => '15.6 inch', 'Resolution' => '1920x1080'],
                    'Graphics' => ['GPU' => 'Intel Iris Xe'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 5
            [
                'name' => 'Intel NUC 13 Pro Mini Desktop',
                'slug' => 'intel-nuc-13-pro-mini-desktop',
                'sku' => 'INT-NUC13-001',
                'category_id' => $cats['desktops'],
                'brand_id' => $brands['intel'],
                'price' => 42000.00,
                'sale_price' => null,
                'stock' => 7,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Compact, powerful mini PC for home and office use.',
                'specs' => [
                    'Processor' => ['CPU' => 'Intel Core i7-1360P', 'Cores' => '12'],
                    'Memory' => ['RAM' => '32GB DDR4 (upgradeable)'],
                    'Storage' => ['SSD' => '512GB NVMe'],
                    'Form Factor' => ['Type' => 'Mini PC'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 6
            [
                'name' => 'MSI MEG Aegis Ti5 Desktop',
                'slug' => 'msi-meg-aegis-ti5-desktop',
                'sku' => 'MSI-AEGIS-001',
                'category_id' => $cats['desktops'],
                'brand_id' => $brands['msi'],
                'price' => 125000.00,
                'sale_price' => 110000.00,
                'stock' => 3,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => 'Flagship gaming desktop with liquid cooling and RGB showcase.',
                'specs' => [
                    'Processor' => ['CPU' => 'Intel Core i9-13900K', 'Cores' => '24'],
                    'Memory' => ['RAM' => '64GB DDR5'],
                    'Storage' => ['SSD' => '2TB NVMe', 'HDD' => '4TB'],
                    'Graphics' => ['GPU' => 'NVIDIA RTX 4090 24GB'],
                    'Cooling' => ['Type' => '360mm AIO Liquid'],
                    'Warranty' => ['Duration' => '2 Years'],
                ],
            ],
            // 7
            [
                'name' => 'ASUS ROG Strix GT35 Desktop',
                'slug' => 'asus-rog-strix-gt35-desktop',
                'sku' => 'ASUS-GT35-001',
                'category_id' => $cats['desktops'],
                'brand_id' => $brands['asus'],
                'price' => 89000.00,
                'sale_price' => null,
                'stock' => 4,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => 'High-performance gaming desktop with ROG aesthetic.',
                'specs' => [
                    'Processor' => ['CPU' => 'Intel Core i7-13700K', 'Cores' => '16'],
                    'Memory' => ['RAM' => '32GB DDR5'],
                    'Storage' => ['SSD' => '1TB NVMe'],
                    'Graphics' => ['GPU' => 'NVIDIA RTX 4080 16GB'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 8
            [
                'name' => 'Intel Core i9-13900K Processor',
                'slug' => 'intel-core-i9-13900k-processor',
                'sku' => 'INT-I9-13900K',
                'category_id' => $cats['components'],
                'brand_id' => $brands['intel'],
                'price' => 18500.00,
                'sale_price' => null,
                'stock' => 20,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => true,
                'description' => 'Intel flagship desktop processor with 24 cores for extreme performance.',
                'specs' => [
                    'Specifications' => ['Cores' => '24', 'Threads' => '32', 'Base Clock' => '3.0GHz', 'Boost Clock' => '5.8GHz', 'TDP' => '125W'],
                    'Memory' => ['Max RAM' => 'DDR5-5600', 'Channels' => 'Dual'],
                    'Socket' => ['Type' => 'LGA1700'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 9
            [
                'name' => 'AMD Ryzen 9 7950X Processor',
                'slug' => 'amd-ryzen-9-7950x-processor',
                'sku' => 'AMD-R9-7950X',
                'category_id' => $cats['components'],
                'brand_id' => $brands['amd'],
                'price' => 22000.00,
                'sale_price' => null,
                'stock' => 12,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => 'AMD\'s most powerful desktop processor for creators and enthusiasts.',
                'specs' => [
                    'Specifications' => ['Cores' => '16', 'Threads' => '32', 'Base Clock' => '4.5GHz', 'Boost Clock' => '5.7GHz', 'TDP' => '170W'],
                    'Memory' => ['Max RAM' => 'DDR5-5200', 'Channels' => 'Dual'],
                    'Socket' => ['Type' => 'AM5'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 10 - out of stock, featured
            [
                'name' => 'NVIDIA RTX 4090 Graphics Card',
                'slug' => 'nvidia-rtx-4090-graphics-card',
                'sku' => 'NV-RTX4090-001',
                'category_id' => $cats['components'],
                'brand_id' => $brands['nvidia'],
                'price' => 55000.00,
                'sale_price' => null,
                'stock' => 0,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => 'The world\'s fastest consumer GPU for 4K gaming and AI workloads.',
                'specs' => [
                    'GPU' => ['Chip' => 'AD102', 'CUDA Cores' => '16384', 'VRAM' => '24GB GDDR6X'],
                    'Performance' => ['TDP' => '450W', 'Power Connector' => '16-pin'],
                    'Display' => ['Outputs' => 'HDMI 2.1, 3x DisplayPort 1.4a'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 11
            [
                'name' => 'AMD Radeon RX 7900 XTX',
                'slug' => 'amd-radeon-rx-7900-xtx',
                'sku' => 'AMD-RX7900XTX',
                'category_id' => $cats['components'],
                'brand_id' => $brands['amd'],
                'price' => 38000.00,
                'sale_price' => null,
                'stock' => 6,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'AMD flagship GPU for 4K gaming with 24GB VRAM.',
                'specs' => [
                    'GPU' => ['Chip' => 'Navi 31', 'Stream Processors' => '12288', 'VRAM' => '24GB GDDR6'],
                    'Performance' => ['TDP' => '355W'],
                    'Display' => ['Outputs' => 'HDMI 2.1, 2x DisplayPort 2.1'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 12 - best seller, sale
            [
                'name' => 'Corsair Vengeance 32GB DDR5 RAM',
                'slug' => 'corsair-vengeance-32gb-ddr5-ram',
                'sku' => 'COR-VEN32-DDR5',
                'category_id' => $cats['components'],
                'brand_id' => $brands['corsair'],
                'price' => 8500.00,
                'sale_price' => 7200.00,
                'stock' => 30,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => true,
                'description' => 'High-speed DDR5 memory for next-gen platforms.',
                'specs' => [
                    'Specifications' => ['Capacity' => '32GB (2x16GB)', 'Speed' => 'DDR5-6000', 'Latency' => 'CL36'],
                    'Voltage' => ['Operating' => '1.35V'],
                    'Warranty' => ['Duration' => 'Lifetime'],
                ],
            ],
            // 13
            [
                'name' => 'MSI MEG Z790 Ace Motherboard',
                'slug' => 'msi-meg-z790-ace-motherboard',
                'sku' => 'MSI-Z790-ACE',
                'category_id' => $cats['components'],
                'brand_id' => $brands['msi'],
                'price' => 15000.00,
                'sale_price' => null,
                'stock' => 8,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Premium Z790 motherboard for Intel 12th/13th Gen processors.',
                'specs' => [
                    'Socket' => ['Type' => 'LGA1700'],
                    'Memory' => ['Slots' => '4', 'Max' => '128GB DDR5'],
                    'Expansion' => ['PCIe' => '5.0 x16'],
                    'Storage' => ['M.2 Slots' => '4', 'SATA Ports' => '6'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 14
            [
                'name' => 'Gigabyte Aorus Gen5 2TB SSD',
                'slug' => 'gigabyte-aorus-gen5-2tb-ssd',
                'sku' => 'GIG-AORUS-2TB',
                'category_id' => $cats['components'],
                'brand_id' => $brands['gigabyte'],
                'price' => 7500.00,
                'sale_price' => null,
                'stock' => 15,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Blazing fast PCIe 5.0 NVMe SSD with 12GB/s read speeds.',
                'specs' => [
                    'Specifications' => ['Capacity' => '2TB', 'Interface' => 'PCIe 5.0 x4', 'Sequential Read' => '12000 MB/s', 'Sequential Write' => '11800 MB/s'],
                    'Form Factor' => ['Type' => 'M.2 2280'],
                    'Warranty' => ['Duration' => '5 Years'],
                ],
            ],
            // 15
            [
                'name' => 'Corsair RM1000x PSU',
                'slug' => 'corsair-rm1000x-psu',
                'sku' => 'COR-RM1000X',
                'category_id' => $cats['components'],
                'brand_id' => $brands['corsair'],
                'price' => 5800.00,
                'sale_price' => null,
                'stock' => 12,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => '1000W 80+ Gold fully modular power supply.',
                'specs' => [
                    'Specifications' => ['Wattage' => '1000W', 'Efficiency' => '80+ Gold', 'Modular' => 'Fully Modular'],
                    'Warranty' => ['Duration' => '10 Years'],
                ],
            ],
            // 16 - best seller
            [
                'name' => 'GameMax Titan Gaming Chair',
                'slug' => 'gamemax-titan-gaming-chair',
                'sku' => 'GMX-TITAN-CHR',
                'category_id' => $cats['gaming-hardware'],
                'brand_id' => $brands['gamemax'],
                'price' => 12500.00,
                'sale_price' => null,
                'stock' => 10,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => true,
                'description' => 'Ergonomic gaming chair with lumbar support and 4D armrests.',
                'specs' => [
                    'Features' => ['Recline' => '90-165 degrees', 'Armrests' => '4D adjustable', 'Material' => 'PU Leather'],
                    'Dimensions' => ['Max Height' => '195cm', 'Max Weight' => '150kg'],
                    'Warranty' => ['Duration' => '2 Years'],
                ],
            ],
            // 17 - featured, sale
            [
                'name' => 'ASUS ROG Swift 360Hz Monitor',
                'slug' => 'asus-rog-swift-360hz-monitor',
                'sku' => 'ASUS-ROG-360HZ',
                'category_id' => $cats['gaming-hardware'],
                'brand_id' => $brands['asus'],
                'price' => 28000.00,
                'sale_price' => 24500.00,
                'stock' => 5,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => '24.5" 360Hz 1080p gaming monitor for competitive esports.',
                'specs' => [
                    'Display' => ['Size' => '24.5 inch', 'Resolution' => '1920x1080', 'Refresh Rate' => '360Hz', 'Panel' => 'IPS', 'Response Time' => '1ms GTG'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 18 - out of stock
            [
                'name' => 'Corsair K100 RGB Keyboard',
                'slug' => 'corsair-k100-rgb-keyboard',
                'sku' => 'COR-K100-RGB',
                'category_id' => $cats['gaming-hardware'],
                'brand_id' => $brands['corsair'],
                'price' => 9800.00,
                'sale_price' => null,
                'stock' => 0,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Flagship mechanical gaming keyboard with OPX optical switches.',
                'specs' => [
                    'Specifications' => ['Switch' => 'Corsair OPX Optical', 'Form Factor' => 'Full Size', 'Backlight' => 'Per-key RGB'],
                    'Connectivity' => ['Type' => 'USB-A'],
                    'Warranty' => ['Duration' => '2 Years'],
                ],
            ],
            // 19 - best seller
            [
                'name' => 'ASUS ROG Gladius III Mouse',
                'slug' => 'asus-rog-gladius-iii-mouse',
                'sku' => 'ASUS-GLADIUS3',
                'category_id' => $cats['gaming-hardware'],
                'brand_id' => $brands['asus'],
                'price' => 4500.00,
                'sale_price' => null,
                'stock' => 20,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => true,
                'description' => 'Ergonomic gaming mouse with swappable switches.',
                'specs' => [
                    'Specifications' => ['DPI' => 'Up to 36000', 'Sensor' => 'ROG AimPoint', 'Buttons' => '7', 'Weight' => '79g'],
                    'Connectivity' => ['Type' => 'USB / Wireless 2.4GHz'],
                    'Warranty' => ['Duration' => '2 Years'],
                ],
            ],
            // 20
            [
                'name' => 'GameMax Vega Gaming Headset',
                'slug' => 'gamemax-vega-gaming-headset',
                'sku' => 'GMX-VEGA-HS',
                'category_id' => $cats['gaming-hardware'],
                'brand_id' => $brands['gamemax'],
                'price' => 3200.00,
                'sale_price' => null,
                'stock' => 18,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Virtual 7.1 surround sound gaming headset with RGB.',
                'specs' => [
                    'Audio' => ['Driver' => '50mm', 'Surround' => '7.1 Virtual', 'Frequency' => '20Hz-20kHz'],
                    'Microphone' => ['Type' => 'Noise-cancelling'],
                    'Connectivity' => ['Type' => '3.5mm + USB adapter'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 21 - out of stock
            [
                'name' => 'MSI MAG PANO 100R Case',
                'slug' => 'msi-mag-pano-100r-case',
                'sku' => 'MSI-PANO100R',
                'category_id' => $cats['components'],
                'brand_id' => $brands['msi'],
                'price' => 5500.00,
                'sale_price' => null,
                'stock' => 0,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Panoramic mid-tower case with 270-degree tempered glass.',
                'specs' => [
                    'Compatibility' => ['Motherboard' => 'E-ATX, ATX, mATX, mITX', 'GPU Max Length' => '400mm', 'CPU Cooler Max' => '175mm'],
                    'Drive Bays' => ['2.5 inch' => '2', '3.5 inch' => '2'],
                    'Fans' => ['Included' => '3x 120mm ARGB'],
                    'Warranty' => ['Duration' => '2 Years'],
                ],
            ],
            // 22
            [
                'name' => 'Corsair iCUE H150i Elite LCD Cooler',
                'slug' => 'corsair-icue-h150i-elite-lcd-cooler',
                'sku' => 'COR-H150I-LCD',
                'category_id' => $cats['components'],
                'brand_id' => $brands['corsair'],
                'price' => 8900.00,
                'sale_price' => null,
                'stock' => 7,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => '360mm AIO liquid cooler with 2.1-inch LCD display.',
                'specs' => [
                    'Radiator' => ['Size' => '360mm', 'Fans' => '3x 120mm PWM'],
                    'Display' => ['Screen' => '2.1 inch LCD', 'Resolution' => '480x480'],
                    'Pump' => ['Speed' => 'Up to 2400 RPM'],
                    'Warranty' => ['Duration' => '5 Years'],
                ],
            ],
            // 23
            [
                'name' => 'ASUS USB-C Hub 7-in-1',
                'slug' => 'asus-usb-c-hub-7-in-1',
                'sku' => 'ASUS-HUB7IN1',
                'category_id' => $cats['accessories'],
                'brand_id' => $brands['asus'],
                'price' => 2800.00,
                'sale_price' => null,
                'stock' => 25,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Expand your laptop connectivity with 7 ports in one compact hub.',
                'specs' => [
                    'Ports' => ['USB-C PD' => '1 (100W)', 'USB-A 3.0' => '3', 'HDMI' => '1 (4K@60Hz)', 'SD Card' => '1', 'microSD' => '1'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 24 - best seller
            [
                'name' => 'Corsair MM700 RGB Mouse Pad',
                'slug' => 'corsair-mm700-rgb-mouse-pad',
                'sku' => 'COR-MM700-RGB',
                'category_id' => $cats['accessories'],
                'brand_id' => $brands['corsair'],
                'price' => 2200.00,
                'sale_price' => null,
                'stock' => 40,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => true,
                'description' => 'XL extended RGB mouse pad with USB pass-through.',
                'specs' => [
                    'Dimensions' => ['Size' => '930x400x4mm'],
                    'Features' => ['RGB' => 'Dynamic 3-Zone', 'USB' => 'USB pass-through port'],
                    'Warranty' => ['Duration' => '2 Years'],
                ],
            ],
            // 25 - out of stock
            [
                'name' => 'ASUS ROG Phone Cooler',
                'slug' => 'asus-rog-phone-cooler',
                'sku' => 'ASUS-ROGCOOL',
                'category_id' => $cats['accessories'],
                'brand_id' => $brands['asus'],
                'price' => 1800.00,
                'sale_price' => null,
                'stock' => 0,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'AeroActive Cooler for ROG Phone with fan and USB-C passthrough.',
                'specs' => [
                    'Compatibility' => ['Devices' => 'ROG Phone Series'],
                    'Cooling' => ['Method' => 'Active Fan + Heat Sink'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 26
            [
                'name' => 'GameMax Razor Gaming Desk',
                'slug' => 'gamemax-razor-gaming-desk',
                'sku' => 'GMX-RAZOR-DSK',
                'category_id' => $cats['accessories'],
                'brand_id' => $brands['gamemax'],
                'price' => 9500.00,
                'sale_price' => null,
                'stock' => 8,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Gaming desk with RGB lighting, cable management, and headset hook.',
                'specs' => [
                    'Dimensions' => ['Size' => '160x80cm', 'Height' => 'Adjustable 72-120cm'],
                    'Features' => ['RGB' => 'LED strip', 'Cable Management' => 'Built-in'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 27 - featured
            [
                'name' => 'MSI Modern AM272 All-in-One',
                'slug' => 'msi-modern-am272-all-in-one',
                'sku' => 'MSI-AM272-001',
                'category_id' => $cats['desktops'],
                'brand_id' => $brands['msi'],
                'price' => 48000.00,
                'sale_price' => null,
                'stock' => 6,
                'status' => 'active',
                'is_featured' => true,
                'is_best_seller' => false,
                'description' => '27-inch All-in-One PC for productivity and creative work.',
                'specs' => [
                    'Processor' => ['CPU' => 'AMD Ryzen 7 5700U', 'Cores' => '8'],
                    'Memory' => ['RAM' => '16GB DDR4'],
                    'Storage' => ['SSD' => '512GB NVMe'],
                    'Display' => ['Size' => '27 inch', 'Resolution' => '1920x1080', 'Type' => 'IPS'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
            // 28 - sale
            [
                'name' => 'Intel Arc A770 Graphics Card',
                'slug' => 'intel-arc-a770-graphics-card',
                'sku' => 'INT-ARCA770',
                'category_id' => $cats['components'],
                'brand_id' => $brands['intel'],
                'price' => 15000.00,
                'sale_price' => 12500.00,
                'stock' => 10,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Intel Arc A770 with 16GB VRAM for 1440p gaming.',
                'specs' => [
                    'GPU' => ['Chip' => 'ACM-G10', 'Shaders' => '4096', 'VRAM' => '16GB GDDR6'],
                    'Performance' => ['TDP' => '225W'],
                    'Display' => ['Outputs' => 'HDMI 2.1, 3x DisplayPort 2.0'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 29
            [
                'name' => 'Gigabyte B760M DS3H Motherboard',
                'slug' => 'gigabyte-b760m-ds3h-motherboard',
                'sku' => 'GIG-B760M-DS3H',
                'category_id' => $cats['components'],
                'brand_id' => $brands['gigabyte'],
                'price' => 4800.00,
                'sale_price' => null,
                'stock' => 18,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Budget B760M microATX motherboard for Intel 12th/13th Gen.',
                'specs' => [
                    'Socket' => ['Type' => 'LGA1700'],
                    'Memory' => ['Slots' => '4', 'Max' => '128GB DDR4'],
                    'Storage' => ['M.2 Slots' => '2', 'SATA Ports' => '4'],
                    'Warranty' => ['Duration' => '3 Years'],
                ],
            ],
            // 30 - out of stock
            [
                'name' => 'GameMax Bluetooth Mechanical Keyboard',
                'slug' => 'gamemax-bluetooth-mechanical-keyboard',
                'sku' => 'GMX-BT-MECH',
                'category_id' => $cats['accessories'],
                'brand_id' => $brands['gamemax'],
                'price' => 3500.00,
                'sale_price' => null,
                'stock' => 0,
                'status' => 'active',
                'is_featured' => false,
                'is_best_seller' => false,
                'description' => 'Wireless mechanical keyboard with Bluetooth 5.0 and 2.4GHz connectivity.',
                'specs' => [
                    'Specifications' => ['Switch' => 'Blue Mechanical', 'Form Factor' => 'TKL 80%', 'Backlight' => 'RGB'],
                    'Connectivity' => ['Type' => 'Bluetooth 5.0 / 2.4GHz / USB-C'],
                    'Battery' => ['Capacity' => '4000mAh'],
                    'Warranty' => ['Duration' => '1 Year'],
                ],
            ],
        ];

        foreach ($products as $index => $productData) {
            $productData['meta_title'] = $productData['meta_title'] ?? ($productData['name'] . ' - Techno Tronics');
            $productData['meta_description'] = $productData['meta_description'] ?? strip_tags(substr($productData['description'], 0, 160));

            $product = Product::updateOrCreate(
                ['sku' => $productData['sku']],
                $productData
            );

            if ($product->wasRecentlyCreated || !$product->images()->exists()) {
                // Create primary placeholder image
                $encodedName = urlencode($productData['name']);
                ProductImage::updateOrCreate(
                    ['product_id' => $product->id, 'is_primary' => true],
                    [
                        'path' => "https://placehold.co/800x600/0f172a/3b82f6?text={$encodedName}",
                        'alt' => $productData['name'],
                        'position' => 0,
                        'is_primary' => true,
                    ]
                );
                // Create secondary image
                $encodedNameSide = urlencode($productData['name'] . ' - Side');
                ProductImage::firstOrCreate(
                    ['product_id' => $product->id, 'position' => 1],
                    [
                        'path' => "https://placehold.co/800x600/1e293b/60a5fa?text={$encodedNameSide}",
                        'alt' => $productData['name'] . ' - Side view',
                        'position' => 1,
                        'is_primary' => false,
                    ]
                );
            }
        }
    }
}
